name = "StructuredDecompositions"
uuid = "ba32925c-6e4c-4640-bed9-b00febeea19a"
authors = ["benjaminmerlinbumpus <benjamin.merlin.bumpus@gmail.com>"]
version = "0.1.0"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
PartialFunctions = "570af359-4316-4cb7-8c74-252c00c2016b"

[compat]
Catlab = "^0.14"
MLStyle = "^0.4"
PartialFunctions = "^1.1"
julia = "^1.7"
